#!/usr/bin/env bash
#
# client-setup.sh - Point a developer machine at the local Ollama server.
#
# Run as your normal user (not root) on the server itself or on any machine in
# the same network:
#
#   ./client-setup.sh                            # server on this machine
#   ./client-setup.sh --server 192.168.1.50      # server elsewhere on the LAN
#
# It checks the connection, then configures:
#   * VS Code "Continue" extension  (~/.continue/config.yaml)  chat + autocomplete
#   * Aider                         (~/.aider.conf.yml)          if --aider
#   * Shell environment              (~/.bashrc)                 OLLAMA_HOST etc.

set -euo pipefail

SERVER="localhost"
CHAT_MODEL=""
AUTOCOMPLETE_MODEL=""
INSTALL_EXT=1
VSIX=""
SETUP_AIDER=0
SETUP_SHELL=1

info() { echo "==> $*"; }
ok()   { echo " ✔  $*"; }
warn() { echo " !!  $*" >&2; }
die()  { echo "ERROR: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
    cat <<EOF
Usage: $0 [options]

  --server HOST[:PORT]   Ollama server (default: localhost:11434)
  --model TAG            Chat model (default: auto-detect from server)
  --autocomplete TAG     Autocomplete model (default: auto-detect, 'none' to skip)
  --vsix FILE            Install the Continue extension from a local .vsix (offline)
  --no-extension         Do not install the Continue VS Code extension
  --aider                Also write ~/.aider.conf.yml for the aider CLI
  --no-shell             Do not add OLLAMA_HOST to ~/.bashrc
  -h, --help             Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --server)        SERVER="${2:?}"; shift 2 ;;
        --model)         CHAT_MODEL="${2:?}"; shift 2 ;;
        --autocomplete)  AUTOCOMPLETE_MODEL="${2:?}"; shift 2 ;;
        --vsix)          VSIX="${2:?}"; shift 2 ;;
        --no-extension)  INSTALL_EXT=0; shift ;;
        --aider)         SETUP_AIDER=1; shift ;;
        --no-shell)      SETUP_SHELL=0; shift ;;
        -h|--help)       usage; exit 0 ;;
        *)               usage >&2; die "Unknown option: $1" ;;
    esac
done

[ "$(id -u)" -eq 0 ] && warn "Running as root: config will be written for root, not your user."
have curl || die "curl is required (sudo apt-get install curl)."

SERVER="${SERVER#http://}"; SERVER="${SERVER%/}"
[[ "$SERVER" == *:* ]] || SERVER="$SERVER:11434"
API="http://$SERVER"

# ------------------------------------------------------------- connectivity ---
info "Checking Ollama server at $API ..."
VERSION_JSON=$(curl -fsS --max-time 5 "$API/api/version" 2>/dev/null) || die "Cannot reach $API.
  - Is the server running?        (on server: systemctl status ollama)
  - Was it installed with --lan?  (needed for other machines)
  - Firewall?                     (on server: sudo ufw status)"
ok "Connected: $VERSION_JSON"

MODELS=$(curl -fsS "$API/api/tags" | grep -oE '"name":"[^"]+"' | cut -d'"' -f4)
[ -n "$MODELS" ] || die "The server has no models installed."
echo "   Models on server: $(echo "$MODELS" | paste -sd' ' -)"

has_model() { echo "$MODELS" | grep -qxF "$1"; }

if [ -z "$CHAT_MODEL" ]; then
    # Prefer the biggest coder instruct model, skip '-base' (autocomplete) models.
    for cand in qwen3-coder:30b qwen2.5-coder:32b qwen2.5-coder:14b qwen2.5-coder:7b \
                qwen2.5-coder:3b qwen2.5-coder:1.5b; do
        if has_model "$cand"; then CHAT_MODEL="$cand"; break; fi
    done
    [ -n "$CHAT_MODEL" ] || CHAT_MODEL=$(echo "$MODELS" | grep -v -- '-base' | head -1)
fi
has_model "$CHAT_MODEL" || die "Model '$CHAT_MODEL' is not on the server."

if [ -z "$AUTOCOMPLETE_MODEL" ]; then
    AUTOCOMPLETE_MODEL=$(echo "$MODELS" | grep -E 'coder:.*-base' | sort -V | head -1 || true)
    [ -n "$AUTOCOMPLETE_MODEL" ] || AUTOCOMPLETE_MODEL="$CHAT_MODEL"
fi
[ "$AUTOCOMPLETE_MODEL" = "none" ] && AUTOCOMPLETE_MODEL=""

echo "   Chat model        : $CHAT_MODEL"
echo "   Autocomplete model: ${AUTOCOMPLETE_MODEL:-<none>}"

backup() { [ -f "$1" ] && cp "$1" "$1.bak.$(date +%Y%m%d%H%M%S)" && echo "   (backed up existing $1)"; return 0; }

# ---------------------------------------------------------------- continue ---
CONT_DIR="$HOME/.continue"
CONT_CFG="$CONT_DIR/config.yaml"
info "Writing Continue config $CONT_CFG"
mkdir -p "$CONT_DIR"
backup "$CONT_CFG"
{
    cat <<EOF
# Generated by local-ai-code/client-setup.sh - local Ollama server, no cloud.
name: Local Qwen
version: 1.0.0
schema: v1
models:
  - name: $CHAT_MODEL (local)
    provider: ollama
    model: $CHAT_MODEL
    apiBase: $API
    roles: [chat, edit, apply]
    defaultCompletionOptions:
      contextLength: 16384
EOF
    if [ -n "$AUTOCOMPLETE_MODEL" ]; then
        cat <<EOF
  - name: $AUTOCOMPLETE_MODEL (autocomplete)
    provider: ollama
    model: $AUTOCOMPLETE_MODEL
    apiBase: $API
    roles: [autocomplete]
EOF
    fi
    cat <<EOF
context:
  - provider: code
  - provider: file
  - provider: currentFile
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
EOF
} > "$CONT_CFG"
ok "Continue configured."

if [ "$INSTALL_EXT" = 1 ]; then
    CODE_BIN=""
    for c in code codium code-insiders; do have "$c" && { CODE_BIN="$c"; break; }; done
    if [ -z "$CODE_BIN" ]; then
        warn "VS Code not found; install it, then the 'Continue' extension (Continue.continue)."
    elif [ -n "$VSIX" ]; then
        info "Installing Continue from $VSIX ..."
        "$CODE_BIN" --install-extension "$VSIX" --force && ok "Continue extension installed."
    elif "$CODE_BIN" --list-extensions 2>/dev/null | grep -qi '^continue\.continue$'; then
        ok "Continue extension already installed."
    else
        info "Installing Continue extension (needs internet; use --vsix FILE when offline) ..."
        if "$CODE_BIN" --install-extension Continue.continue; then
            ok "Continue extension installed."
        else
            warn "Could not install extension. Offline? Use --vsix with the file from the bundle."
        fi
    fi
fi

# ------------------------------------------------------------------- aider ---
if [ "$SETUP_AIDER" = 1 ]; then
    AIDER_CFG="$HOME/.aider.conf.yml"
    info "Writing $AIDER_CFG"
    backup "$AIDER_CFG"
    cat > "$AIDER_CFG" <<EOF
# Generated by local-ai-code/client-setup.sh
model: ollama_chat/$CHAT_MODEL
check-update: false
analytics-disable: true
show-release-notes: false
EOF
    have aider || warn "aider not installed (pip install aider-chat), config written anyway."
    ok "aider configured (it reads OLLAMA_API_BASE from your shell)."
fi

# ------------------------------------------------------------------- shell ---
if [ "$SETUP_SHELL" = 1 ]; then
    RC="$HOME/.bashrc"
    MARK="# >>> local-ai-code >>>"
    END="# <<< local-ai-code <<<"
    if [ -f "$RC" ] && grep -qF "$MARK" "$RC"; then
        sed -i "/$MARK/,/$END/d" "$RC"
    fi
    cat >> "$RC" <<EOF
$MARK
export OLLAMA_HOST="$SERVER"
export OLLAMA_API_BASE="$API"
export OPENAI_API_BASE="$API/v1"
$END
EOF
    ok "Added OLLAMA_HOST / OLLAMA_API_BASE to $RC (open a new terminal)."
fi

# -------------------------------------------------------------------- test ---
info "Sending a test prompt to $CHAT_MODEL ..."
REPLY=$(curl -fsS --max-time 300 "$API/api/generate" \
    -d "{\"model\":\"$CHAT_MODEL\",\"prompt\":\"Write a one-line Python hello world. Code only.\",\"stream\":false,\"options\":{\"num_predict\":40}}" \
    | sed -nE 's/.*"response":"((\\.|[^"\\])*)".*/\1/p' || true)
if [ -n "$REPLY" ]; then ok "Model replied: $(printf '%b' "$REPLY" | head -3)"; else warn "Test prompt failed."; fi

cat <<EOF

All set. Open VS Code, click the Continue icon in the sidebar and start chatting;
tab-autocomplete uses ${AUTOCOMPLETE_MODEL:-<disabled>}. Everything runs on $SERVER.

Terminal:  OLLAMA_HOST=$SERVER ollama run $CHAT_MODEL   (needs the ollama CLI)
           curl $API/v1/chat/completions ...            (OpenAI-compatible)
EOF
